name: kora
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: ^0.13.4
  get_storage: ^2.1.1
  pin_code_fields: ^7.4.0
  email_auth: ^1.0.0
  step_progress_indicator: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  web_socket_channel: ^2.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.18

flutter_native_splash:
  image:  assets/images/font-pic.png
  background_image: "assets/images/background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/backgroundSplash2.png
    - assets/images/validate.png
    - assets/images/error.png
    - assets/images/scanning.png
    - assets/images/background.png
    - assets/images/font-pic.png
    - assets/images/unite.png
    - assets/images/plant_background.png
    - assets/images/backgroundProgress.png

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf